// Generated by CoffeeScript 1.8.0
(function() {
  var RSVP, github;

  RSVP = require('rsvp');

  github = require('octonode');

  module.exports = function(data) {
    return new RSVP.Promise(function(resolve) {
      var creds;
      creds = data.credentials;
      console.log('  Connecting client:'.green);
      console.log(("    username:     " + creds.username).grey);
      console.log(("    password:     " + (creds.password.replace(/./g, '*'))).grey);
      console.log(("    repo:         " + creds.repo).grey);
      data.client = github.client({
        username: creds.username,
        password: creds.password
      });
      return data.client.limit(function(error, left, max) {
        if (error != null) {
          return console.log(("  " + error.message).red);
        } else {
          console.log(("\n  Requests until API limit: " + left + "\n").yellow);
          return resolve(data);
        }
      });
    });
  };

}).call(this);
