// Generated by CoffeeScript 1.8.0
(function() {
  var RSVP, github;

  RSVP = require('rsvp');

  github = require('octonode');

  module.exports = function(data) {
    return new RSVP.Promise(function(resolve) {
      var creds;
      creds = data.credentials;
      console.log("\n...getting client\n username:     " + creds.username + "\n password:     " + (creds.password.replace(/./g, '*')) + "\n repo:         " + creds.repo + "\n");
      data.client = github.client({
        username: creds.username,
        password: creds.password
      });
      return data.client.limit(function(error, left, max) {
        if (error != null) {
          console.log(error.message);
        }
        console.log("   requests until limit: " + left);
        return resolve(data);
      });
    });
  };

}).call(this);
