// Generated by CoffeeScript 1.9.1
(function() {
  module.exports = [
    {
      name: 'username',
      description: 'Username'
    }, {
      name: 'password',
      hidden: true,
      description: 'Password'
    }, {
      name: 'repo',
      description: 'Repo URL: like vigetlabs/prchive'
    }
  ];

}).call(this);
