// Generated by CoffeeScript 1.8.0
(function() {
  var RSVP, fs, prompt, _;

  RSVP = require('rsvp');

  fs = require('fs');

  prompt = require('prompt');

  _ = require('underscore');

  module.exports = new RSVP.Promise(function(resolve) {
    var data;
    data = {};
    if (_(process.argv).contains('--config')) {
      data.credentials = JSON.parse(fs.readFileSync('.config.json'));
      return resolve(data);
    } else {
      return prompt.get(require('./config_credentials'), function(err, result) {
        data.credentials = result;
        return resolve(data);
      });
    }
  });

}).call(this);
