// Generated by CoffeeScript 1.8.0
(function() {
  var RSVP, fs, moment;

  RSVP = require('rsvp');

  fs = require('fs');

  moment = require('moment');

  module.exports = function(data) {
    return new RSVP.Promise(function(resolve) {
      var reponame, timestamp;
      reponame = data.credentials.repo.split('/')[1];
      timestamp = moment().format('YYYY-MM-DD-HHmmss');
      data.dirname = "" + reponame + "-media-archive--" + timestamp;
      return fs.mkdir(data.dirname, function() {
        console.log(("\n  Created directory: " + data.dirname).green);
        return resolve(data);
      });
    });
  };

}).call(this);
