// Generated by CoffeeScript 1.8.0
(function() {
  var RSVP, fs, _;

  RSVP = require('rsvp');

  fs = require('fs');

  _ = require('underscore');

  module.exports = function(data) {
    return new RSVP.Promise(function(resolve) {
      var linkedMedia, localMedia, urls;
      linkedMedia = '';
      localMedia = '';
      urls = '';
      _(data.prs).each(function(pr) {
        return _(pr.urls).each(function(url) {
          if (url.match(/.mov$/)) {
            linkedMedia += "<embed src='" + url + "' width='800' height='450'></embed>\n";
          } else {
            linkedMedia += "<img src='" + url + "'>\n";
          }
          return urls += "" + url + "\n";
        });
      });
      _(data.prs).each(function(pr) {
        return _(pr.filenames).each(function(filename) {
          if (filename.match(/.mov$/)) {
            return localMedia += "<embed src='" + filename + "' width='800' height='450'></embed>\n";
          } else {
            return localMedia += "<img src='" + filename + "'>\n";
          }
        });
      });
      fs.writeFile("" + data.dirname + "/linked-media.html", linkedMedia);
      fs.writeFile("" + data.dirname + "/local-media.html", localMedia);
      fs.writeFile("" + data.dirname + "/urls.txt", urls);
      return resolve(data);
    });
  };

}).call(this);
