// Generated by CoffeeScript 1.8.0
(function() {
  var RSVP, fs, _;

  RSVP = require('rsvp');

  fs = require('fs');

  _ = require('underscore');

  module.exports = function(data) {
    return new RSVP.Promise(function(resolve) {
      var images, urls;
      images = '';
      urls = '';
      _(data.prs).each(function(pr) {
        return _(pr.urls).each(function(url) {
          images += "<img src='" + url + "'>\n";
          return urls += "" + url + "\n";
        });
      });
      fs.writeFile("" + data.dirname + "/images.html", images);
      fs.writeFile("" + data.dirname + "/urls.txt", urls);
      return resolve(data);
    });
  };

}).call(this);
