// Generated by CoffeeScript 1.9.1
(function() {
  var RSVP, _, fs;

  RSVP = require('rsvp');

  fs = require('fs');

  _ = require('underscore');

  module.exports = function(data) {
    return new RSVP.Promise(function(resolve) {
      var linkedMedia, localMedia, urls;
      linkedMedia = '';
      localMedia = '';
      urls = '';
      data.docdirname = data.dirname + "/docs";
      fs.mkdirSync(data.docdirname);
      _(data.prs).each(function(pr) {
        return _(pr.files).each(function(file) {
          if (file.name.match(/.mov$/)) {
            linkedMedia += "<embed src='" + file.url + "' width='800' height='450'></embed>\n";
          } else {
            linkedMedia += "<img src='" + file.url + "'>\n";
          }
          return urls += file.url + "\n";
        });
      });
      _(data.prs).each(function(pr) {
        return _(pr.files).each(function(file) {
          if (file.name.match(/.mov$/)) {
            return localMedia += "<embed src='../" + file.name + "' width='800' height='450'></embed>\n";
          } else {
            return localMedia += "<img src='../" + file.name + "'>\n";
          }
        });
      });
      fs.writeFile(data.docdirname + "/linked-media.html", linkedMedia);
      fs.writeFile(data.docdirname + "/local-media.html", localMedia);
      fs.writeFile(data.docdirname + "/urls.txt", urls);
      return resolve(data);
    });
  };

}).call(this);
