// Generated by CoffeeScript 1.8.0
(function() {
  var RSVP, _;

  RSVP = require('rsvp');

  _ = require('underscore');

  module.exports = function(data) {
    return new RSVP.Promise(function(resolve) {
      var count;
      count = _(data.prs).reduce(function(memo, pr) {
        return memo + pr.files.length;
      }, 0);
      console.log(("\n  Done! " + count + " items saved in:").green);
      console.log(("  " + __dirname + "/" + data.dirname + "\n").green.bold);
      return resolve(data);
    });
  };

}).call(this);
