// Generated by CoffeeScript 1.8.0
(function() {
  var RSVP, _;

  RSVP = require('rsvp');

  _ = require('underscore');

  module.exports = function(data) {
    return new RSVP.Promise(function(resolve) {
      var count;
      count = _(data.prs).reduce(function(memo, pr) {
        return memo + pr.urls.length;
      }, 0);
      console.log("Done! " + count + " items saved in " + data.dirname);
      return resolve(data);
    });
  };

}).call(this);
