// Generated by CoffeeScript 1.9.1
(function() {
  var RSVP;

  RSVP = require('rsvp');

  module.exports = function(data, i) {
    return new RSVP.Promise(function(resolve) {
      return data.repo.prs({
        page: i,
        per_page: 100,
        state: 'closed'
      }, function(error, prs) {
        if (error != null) {
          console.log(error.message).red;
        }
        data.prs = data.prs.concat(prs);
        return resolve();
      });
    });
  };

}).call(this);
