// Generated by CoffeeScript 1.8.0
(function() {
  var RSVP, httpsync, _;

  RSVP = require('rsvp');

  _ = require('underscore');

  httpsync = require('httpsync');

  module.exports = function(data) {
    return new RSVP.Promise(function(resolve) {
      console.log('...parsing');
      _(data.prs).each(function(pr) {
        var matches;
        pr.urls = [];
        matches = pr.body.match(/(https?:\/\/)([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?\b/g);
        matches = _(matches).map((function(_this) {
          return function(url) {
            var match, req;
            match = url.match(/^http:\/\/cl\.ly/);
            if (match != null) {
              url = url.replace(/[a-zA-Z]\.[a-z]*$/, '');
              console.log(url);
              req = httpsync.request({
                url: url,
                method: 'GET',
                headers: {
                  Accept: 'application/json'
                }
              });
              return JSON.parse(req.end().data.toString()).remote_url;
            } else {
              return url;
            }
          };
        })(this));
        if (matches != null) {
          return pr.urls = pr.urls.concat(matches);
        }
      });
      return resolve(data);
    });
  };

}).call(this);
