// Generated by CoffeeScript 1.8.0
(function() {
  var RSVP, _;

  RSVP = require('rsvp');

  _ = require('underscore');

  module.exports = function(data) {
    return new RSVP.Promise(function(resolve) {
      console.log('...parsing');
      _(data.prs).each(function(pr) {
        var matches, urls;
        pr.urls = [];
        matches = pr.body.match(/\(http.*?\.[a-zA-Z]+\)/i);
        if (matches != null) {
          urls = _(matches).map(function(match) {
            return match.slice(1, -1);
          });
          return pr.urls = pr.urls.concat(urls);
        }
      });
      return resolve(data);
    });
  };

}).call(this);
