// Generated by CoffeeScript 1.9.1
(function() {
  var RSVP, _, pad, pluralize;

  RSVP = require('rsvp');

  _ = require('underscore');

  pluralize = require('pluralize');

  pad = require('pad');

  module.exports = function(data) {
    return new RSVP.Promise(function(resolve) {
      var i, prPromises;
      data.prs = [];
      prPromises = (function() {
        var j, results;
        results = [];
        for (i = j = 1; j <= 10; i = ++j) {
          results.push(require('./get_pr')(data, i));
        }
        return results;
      })();
      return RSVP.all(prPromises).then(function() {
        var maxNumLength;
        console.log(("  " + data.prs.length + " " + (pluralize('PR', data.prs.length)) + " found:").green);
        data.prs = _(data.prs).map(function(pr) {
          return _(pr).pick('body', 'title', 'number');
        });
        _(data.prs).each(function(pr) {
          return console.log(("    " + pr.title).grey);
        });
        maxNumLength = _(data.prs).max(function(pr) {
          return pr.number.toString().length;
        }).number.toString().length;
        _(data.prs).each(function(pr) {
          return pr.number = pad(maxNumLength, pr.number.toString(), 0);
        });
        return resolve(data);
      });
    });
  };

}).call(this);
