// Generated by CoffeeScript 1.8.0
(function() {
  var RSVP, pluralize, _;

  RSVP = require('rsvp');

  _ = require('underscore');

  pluralize = require('pluralize');

  module.exports = function(data) {
    return new RSVP.Promise(function(resolve) {
      return data.repo.prs({
        per_page: 100,
        state: 'all'
      }, function(error, prs) {
        if (error != null) {
          console.log(error.message);
        }
        data.prs = _(prs).map(function(pr) {
          return _(pr).pick('body', 'title');
        });
        console.log(("  " + data.prs.length + " " + (pluralize('PR', data.prs.length)) + " found:").green);
        _(data.prs).each(function(pr) {
          return console.log(("    " + pr.title).grey);
        });
        return resolve(data);
      });
    });
  };

}).call(this);
