// Generated by CoffeeScript 1.8.0
(function() {
  var RSVP, _;

  RSVP = require('rsvp');

  _ = require('underscore');

  module.exports = function(data) {
    return new RSVP.Promise(function(resolve) {
      console.log('...getting prs');
      return data.repo.prs({
        per_page: 100,
        state: 'all'
      }, function(error, prs) {
        if (error != null) {
          console.log(error.message);
        }
        data.prs = _(prs).map(function(pr) {
          return _(pr).pick('body', 'title');
        });
        return resolve(data);
      });
    });
  };

}).call(this);
