// Generated by CoffeeScript 1.8.0
(function() {
  var RSVP;

  RSVP = require('rsvp');

  module.exports = function(data) {
    return new RSVP.Promise(function(resolve) {
      console.log('...getting repo');
      data.repo = data.client.repo(data.credentials.repo);
      return data.repo.info(function(error, repoData) {
        if (error != null) {
          console.log(error.message);
        }
        data.repoData = repoData;
        return resolve(data);
      });
    });
  };

}).call(this);
