// Generated by CoffeeScript 1.8.0
(function() {
  var RSVP, filesize, fs, httpSync, url, _;

  RSVP = require('rsvp');

  _ = require('underscore');

  httpSync = require('http-sync');

  fs = require('fs');

  url = require('url');

  filesize = require('filesize');

  module.exports = function(data) {
    return new RSVP.Promise(function(resolve) {
      console.log("\n  Saving files:".green);
      _(data.prs).each(function(pr) {
        return _(pr.urls).each(function(mediaUrl) {
          var filename, path, req;
          filename = mediaUrl.substring(mediaUrl.lastIndexOf('/') + 1);
          path = "" + data.dirname + "/" + filename;
          req = httpSync.request({
            protocol: url.parse(mediaUrl).protocol,
            host: url.parse(mediaUrl).host,
            path: url.parse(mediaUrl).pathname
          });
          fs.writeFileSync(path, req.end().body);
          return console.log(("    " + filename + " (" + (filesize(fs.statSync('./' + path).size)) + ")").grey);
        });
      });
      return resolve(data);
    });
  };

}).call(this);
