// Generated by CoffeeScript 1.8.0
(function() {
  var RSVP, fs, http, https, _;

  RSVP = require('rsvp');

  _ = require('underscore');

  http = require('http');

  https = require('https');

  fs = require('fs');

  module.exports = function(data) {
    return new RSVP.Promise(function(resolve) {
      console.log('...saving');
      _(data.prs).each(function(pr) {
        pr.filenames = [];
        return _(pr.urls).each(function(url) {
          var file, filename, library, protocol, request;
          filename = url.substring(url.lastIndexOf('/') + 1);
          pr.filenames.push(filename);
          file = fs.createWriteStream("" + data.dirname + "/" + filename);
          protocol = url.match(/^http(s|)/)[0];
          library = protocol === 'http' ? http : https;
          return request = library.get(url, function(response) {
            return response.pipe(file);
          });
        });
      });
      return resolve(data);
    });
  };

}).call(this);
